Updating release for 1.1-12 * Instance Metadata Service calls now use IMDSv2 * cURL handling has been rewritten to avoid the need for eval's * Various shellcheck corrections have been added * A few missing copyright notices have been added

diff --git a/src/bin/eic_curl_authorized_keys b/src/bin/eic_curl_authorized_keys
--- a/src/bin/eic_curl_authorized_keys
+++ b/src/bin/eic_curl_authorized_keys
@@ -20,16 +20,37 @@ set -e
 # Set umask so only we can touch temp files
 umask 077
 
-curl_cmd="/usr/bin/curl -s -f -m 1"
+IMDS="http://169.254.169.254/latest/meta-data"
+
+# cURL wrapper to ensure we always use the desired flags
+curl_cmd () {
+    /usr/bin/curl -s -f -m 1 -H "${1}" "${2}"
+}
+
+# Fetch the IMDSv2 access token.  5 seconds is overall AKC timeout so we use that.
+IMDS_TOKEN="$(/usr/bin/curl -s -f -m 1 -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 5")"
+token_exit="${?}"
+if [ "${token_exit}" -ne 0 ] ; then
+    /usr/bin/logger -i -p authpriv.info "EC2 Instance Connect failed to establish trust with Instance Metadata Service"
+    exit 255
+fi
+if [ -z "${IMDS_TOKEN}" ] ; then
+    # Fast fail
+    /usr/bin/logger -i -p authpriv.info "EC2 Instance Connect failed to get a token to invoke Instance Metadata Service"
+    exit 255
+fi
+
+IMDS_TOKEN_HEADER="X-aws-ec2-metadata-token: ${IMDS_TOKEN}"
 
 # Verify the instance ID itself
-instance=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/instance-id/")
+# Note: if IMDSv1 is disabled here and IMDS_TOKEN is unset we fast-fail out right now.
+instance=$(curl_cmd "${IMDS_TOKEN_HEADER}" "${IMDS}/instance-id/")
 if [ -z "${instance}" ] ; then
   exit 0
 fi
 # Validate the instance ID is i-abcd1234 (8 or 17 char, hex)
 # We have it buffered to 32 chars to futureproof any further EC2 format changes (given some other EC2 resources are already 32 char)
-/bin/echo "${instance}" | /bin/grep -Eq "^i-[0-9a-f]{8,32}$" || exit 0
+/bin/echo "${instance}" | /usr/bin/head -n 1 | /bin/grep -Eq "^i-[0-9a-f]{8,32}$" || exit 0
 # Verify we have an EC2 uuid
 if [ ! -f /sys/hypervisor/uuid ] ; then
     # Nitro, switch to DMI check
@@ -37,12 +58,12 @@ if [ ! -f /sys/hypervisor/uuid ] ; then
         # We're out of options.  This is definitely not an instance.
         /usr/bin/logger -i -p authpriv.info "EC2 Instance Connect was invoked on a non-instance and will do nothing."
         exit 0
-    elif [ ! $(/bin/cat /sys/devices/virtual/dmi/id/board_asset_tag) = "${instance}" ] ; then
+    elif [ "$(/bin/cat /sys/devices/virtual/dmi/id/board_asset_tag)" != "${instance}" ] ; then
         # The board_asset_tag does not match the instance id.  This is not a valid instance.
         /usr/bin/logger -i -p authpriv.info "EC2 Instance Connect was invoked on a non-instance and will do nothing."
         exit 0
     fi
-elif [ ! $(/usr/bin/cut -c1-3 < /sys/hypervisor/uuid) = "ec2" ] ; then
+elif [ "$(/usr/bin/cut -c1-3 < /sys/hypervisor/uuid)" != "ec2" ] ; then
     # Leading bytes are not "ec2"
     /usr/bin/logger -i -p authpriv.info "EC2 Instance Connect was invoked on a non-instance and will do nothing."
     exit 0
@@ -59,76 +80,84 @@ if [ -z "${1}" ] ; then
 fi
 
 /usr/bin/id -u "${1}" > /dev/null 2>&1
-if [ $? -ne 0 ] ; then
+id_exit="${?}"
+if [ "${id_exit}" -ne 0 ] ; then
     # User doesn't actually exist.  Let sshd deal with it.
     exit 0
 fi
 
 # Verify that we have active keys.  Fast-exit if we do not.
-if [ $(eval "${curl_cmd} -o /dev/null -I -w %{http_code} \"http://169.254.169.254/latest/meta-data/managed-ssh-keys/active-keys/${1}/\"") -eq 404 ]
+keys_status="$(/usr/bin/curl -s -f -m 1 -H "${IMDS_TOKEN_HEADER}" -o /dev/null -I -w %{http_code} "${IMDS}/managed-ssh-keys/active-keys/${1}/")"
+if [ "${keys_status}" != "200" ]
 then
     # No keys for this user.   Nothing to do.
     exit 0
 fi
 # We are not checking format here - that is parse_authorized_keys's job
 
-zone=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/placement/availability-zone/")
-if [ $? -ne 0 ]
+zone=$(curl_cmd "${IMDS_TOKEN_HEADER}" "${IMDS}/placement/availability-zone/")
+zone_exit="${?}"
+if [ "${zone_exit}" -ne 0 ]
 then
-    exit 255
+    exit "${zone_exit}"
 fi
 # Validate the zone is aa-bb-#c (or aa-bb-cc-#d for special partitions like AWS GovCloud)
-/bin/echo "${zone}" | /bin/grep -Eq "^([a-z]+-){2,3}[0-9][a-z]$" || exit 255
+/bin/echo "${zone}" | /usr/bin/head -n 1 | /bin/grep -Eq "^([a-z]+-){2,3}[0-9][a-z]$" || exit 255
 
 region=$(/bin/echo "${zone}" | /bin/sed -n 's/\(\([a-z]\+-\)\+[0-9]\+\).*/\1/p')
-domain=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/services/domain/")
-if [ $? -ne 0 ]
+domain=$(curl_cmd "${IMDS_TOKEN_HEADER}" "${IMDS}/services/domain/")
+domain_exit="${?}"
+if [ "${domain_exit}" -ne 0 ]
 then
-    exit 255
+    exit "${domain_exit}"
 fi
 
 expected_signer=$(/usr/bin/printf 'managed-ssh-signer.%s.%s' "${region}" "${domain}")
 
 userpath=$(/bin/mktemp -d /dev/shm/eic-XXXXXXXX)
-trap 'rm -rf "${userpath}"' EXIT
+trap 'rm -rf "${userpath:?}"' EXIT
 
 # Read the current signer cert
 # This will overwrite whatever currently exists, so it will remain up-to-date
-certificate=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/managed-ssh-keys/signer-cert/")
-if [ -z "${certificate}" ]
+certificate=$(curl_cmd "${IMDS_TOKEN_HEADER}" "${IMDS}/managed-ssh-keys/signer-cert/")
+cert_exit="${?}"
+if [ "${cert_exit}" -ne 0 ] || [ -z "${certificate}" ]
 then
-  exit 255
+    exit "${cert_exit}"
 fi
 # parse_authorized_keys will verify this
 
 # Read the signer OCSP staples
-staple_paths=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/managed-ssh-keys/signer-ocsp/")
-if [ $? -ne 0 ]
+staple_paths=$(curl_cmd "${IMDS_TOKEN_HEADER}" "${IMDS}/managed-ssh-keys/signer-ocsp/")
+staple_exit="${?}"
+if [ "${staple_exit}" -ne 0 ]
 then
-    exit 255
+    exit "${staple_exit}"
 fi
 
 ocsp_path=$(/bin/mktemp -d "${userpath}/eic-ocsp-XXXXXXXX")
 for word in $staple_paths
 do
-    eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/managed-ssh-keys/signer-ocsp/${word}" | /usr/bin/base64 -d > "${ocsp_path}/${word}"
-    if [ $? -ne 0 ]
+    curl_cmd "${IMDS_TOKEN_HEADER}" "${IMDS}/managed-ssh-keys/signer-ocsp/${word}" | /usr/bin/base64 -d > "${ocsp_path}/${word}"
+    staple_exit="${?}"
+    if [ "${staple_exit}" -ne 0 ]
     then
-        exit 255
+        exit "${staple_exit}"
     fi
     /bin/chmod 400 "${ocsp_path}/${word}" # Disable access to staple file
 done
 # parse_authorized_keys will verify these
 
 # Invoke key parser (will automagically echo the results)
-curl_command="${curl_cmd} \"http://169.254.169.254/latest/meta-data/managed-ssh-keys/active-keys/${1}/\""
+keys_file="${userpath}/eic-keys"
+curl_cmd "${IMDS_TOKEN_HEADER}" "${IMDS}/managed-ssh-keys/active-keys/${1}/" > "${keys_file}"
 DIR="$( cd "$( dirname "${0}" )" && pwd )"
 ca_path=/etc/ssl/certs
 if [ -z "${2}" ] ; then
-    output=$($DIR/eic_parse_authorized_keys -x false -r "${curl_command}" -o "${OPENSSL}" -d "${userpath}" -s "${certificate}" -i "${instance}" -c "${expected_signer}" -a "${ca_path}" -v "${ocsp_path}")
+    output="$("${DIR}/eic_parse_authorized_keys" -x false -p "${keys_file}" -o "${OPENSSL}" -d "${userpath}" -s "${certificate}" -i "${instance}" -c "${expected_signer}" -a "${ca_path}" -v "${ocsp_path}")"
     exitcode=$? # not quote-escaped since this must be numeric 0-255
 else
-    output=$($DIR/eic_parse_authorized_keys -x false -r "${curl_command}" -o "${OPENSSL}" -d "${userpath}" -s "${certificate}" -i "${instance}" -c "${expected_signer}" -a "${ca_path}" -v "${ocsp_path}" -f "${2}")
+    output="$("${DIR}/eic_parse_authorized_keys" -x false -p "${keys_file}" -o "${OPENSSL}" -d "${userpath}" -s "${certificate}" -i "${instance}" -c "${expected_signer}" -a "${ca_path}" -v "${ocsp_path}" -f "${2}")"
     exitcode=$? # not quote-escaped since this must be numeric 0-255
 fi
 
diff --git a/src/bin/eic_harvest_hostkeys b/src/bin/eic_harvest_hostkeys
--- a/src/bin/eic_harvest_hostkeys
+++ b/src/bin/eic_harvest_hostkeys
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 #
@@ -17,16 +17,21 @@ set -e
 
 umask 077
 
-curl_cmd="/usr/bin/curl -s -f -m 1"
+# Fetch the IMDSv2 access token.  5 seconds is overall AKC timeout so we use that.
+IMDS_TOKEN="$(/usr/bin/curl -s -f -m 1 -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 5")"
+if [ -z "${IMDS_TOKEN}" ] ; then
+    # Fast fail
+    exit 255
+fi
 
 # Verify the instance ID itself
-instance=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/instance-id/")
+instance=$(/usr/bin/curl -s -f -m 1 -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" "http://169.254.169.254/latest/meta-data/instance-id/")
 if [ -z "${instance}" ] ; then
   exit 255
 fi
 # Validate the instance ID is i-abcd1234 (8 or 17 char, hex)
 # We have it buffered to 32 chars to futureproof any further EC2 format changes (given some other EC2 resources are already 32 char)
-/bin/echo "${instance}" | /bin/grep -Eq "^i-[0-9a-f]{8,32}$" || exit 255
+/bin/echo "${instance}" | /usr/bin/head -n 1 | /bin/grep -Eq "^i-[0-9a-f]{8,32}$" || exit 255
 
 # Verify we have an EC2 uuid
 if [ ! -f /sys/hypervisor/uuid ] ; then
@@ -34,11 +39,11 @@ if [ ! -f /sys/hypervisor/uuid ] ; then
     if [ ! -f /sys/devices/virtual/dmi/id/board_asset_tag ] ; then
         # We're out of options.  This is definitely not an instance.
         exit 255
-    elif [ ! $(/bin/cat /sys/devices/virtual/dmi/id/board_asset_tag) = "${instance}" ] ; then
+    elif [ "$(/bin/cat /sys/devices/virtual/dmi/id/board_asset_tag)" != "${instance}" ] ; then
         # The board_asset_tag does not match the instance id.  This is not a valid instance.
         exit 255
     fi
-elif [ ! $(/usr/bin/cut -c1-3 < /sys/hypervisor/uuid) = "ec2" ] ; then
+elif [ "$(/usr/bin/cut -c1-3 < /sys/hypervisor/uuid)" != "ec2" ] ; then
     # Leading bytes are not "ec2"
     exit 255
 fi
@@ -46,7 +51,7 @@ fi
 # Calculate the SHA256 of a given string
 # sha256 [string]
 sha256 () {
-    /bin/echo -n "${val}" | /usr/bin/sha256sum | /bin/sed 's/\s.*$//'
+    /bin/echo -n "${1}" | /usr/bin/sha256sum | /bin/sed 's/\s.*$//'
 }
 
 # Sign a message with a given key
@@ -58,15 +63,16 @@ sign () {
 # Derive a sigv4 signing key for the given secret
 # get_sigv4_key [key] [datestamp] [region name] [service name]
 getsigv4key () {
-    local base=$(/bin/echo -n "AWS4${1}" | /usr/bin/od -A n -t x1 | /bin/sed ':a;N;$!ba;s/[\n ]//g')
-    local kdate=$(sign "${base}" "${2}")
-    local kregion=$(sign "${kdate}" "${3}")
-    local kservice=$(sign "${kregion}" "${4}")
+    base="$(/bin/echo -n "AWS4${1}" | /usr/bin/od -A n -t x1 | /bin/sed ':a;N;$!ba;s/[\n ]//g')"
+    kdate="$(sign "${base}" "${2}")"
+    kregion="$(sign "${kdate}" "${3}")"
+    kservice="$(sign "${kregion}" "${4}")"
     sign "${kservice}" "aws4_request"
 }
 
 # Verify that we have instance identity credentials.  Fast-exit if we do not.
-if [ $(eval "${curl_cmd} -o /dev/null -I -w %{http_code} http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance/") -ne 200 ]
+creds_status="$(/usr/bin/curl -s -f -m 1 -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" -o /dev/null -I -w %{http_code} "http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance/")"
+if [ "${creds_status}" != "200" ]
 then
     # No keys for this user.   Nothing to do.
     exit 0
@@ -84,23 +90,22 @@ userpath=$(/bin/mktemp -d /dev/shm/eic-hostkey-XXXXXXXX)
 trap 'rm -rf "${userpath}"' EXIT
 
 #Get zone information
-zone=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/placement/availability-zone/")
-if [ $? -ne 0 ]
+zone=$(/usr/bin/curl -s -f -m 1 -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" "http://169.254.169.254/latest/meta-data/placement/availability-zone/")
+zone_exit="${?}"
+if [ "${zone_exit}" -ne 0 ]
 then
-    exit 255
+    exit "${zone_exit}"
 fi
 
 # Validate the zone
-if [[ ! "${zone}" =~ ^([a-z]+-){2,3}[0-9][a-z]$ ]]
-then
-    exit 255
-fi
+/bin/echo "${zone}" | /usr/bin/head -n 1 | /bin/grep -Eq "^([a-z]+-){2,3}[0-9][a-z]$" || exit 255
 
 # Get domain for calls
-domain=$(eval "${curl_cmd}" "http://169.254.169.254/latest/meta-data/services/domain/")
-if [ $? -ne 0 ]
+domain=$(/usr/bin/curl -s -f -m 1 -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" "http://169.254.169.254/latest/meta-data/services/domain/")
+domain_exit="${?}"
+if [ "${domain_exit}" -ne 0 ]
 then
-    exit 255
+    exit "${domain_exit}"
 fi
 
 #Extract region from zone
@@ -108,18 +113,16 @@ region=$(/bin/echo "${zone}" | /bin/sed -n 's/\(\([a-z]\+-\)\+[0-9]\+\).*/\1/p')
 
 hostkeys=$(/bin/echo "${keys:?}")
 
-accountId=$(eval "${curl_cmd} http://169.254.169.254/latest/dynamic/instance-identity/document" | /bin/grep -oP '(?<="accountId" : ")[^"]*(?=")')
-if [[ ! "${accountId}" =~ ^[0-9]{12}$ ]]
-then
-    exit 255
-fi
+accountId=$(/usr/bin/curl -s -f -m 1 -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" "http://169.254.169.254/latest/dynamic/instance-identity/document" | /bin/grep -oP '(?<="accountId" : ")[^"]*(?=")')
+/bin/echo "${accountId}" | /usr/bin/head -n 1 | /bin/grep -Eq "^[0-9]{12}$" || exit 255
 val='{"AccountID":"'${accountId}'","AvailabilityZone":"'${zone}'","HostKeys":['${hostkeys}'],"InstanceId":"'${instance}'"}'
 
 # Pull the creds we need for the call
-creds=$(eval "${curl_cmd} http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance/")
-if [ $? -ne 0 ] ; then
+creds=$(/usr/bin/curl -s -f -m 1 -H "X-aws-ec2-metadata-token: ${IMDS_TOKEN}" "http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance/")
+creds_exit="${?}"
+if [ "${creds_exit}" -ne 0 ] ; then
     # We failed to load instance-identity credentials
-    exit 255
+    exit "${creds_exit}"
 fi
 AWS_ACCESS_KEY_ID=$(/bin/echo "${creds}" | /bin/sed -n 's/.*"AccessKeyId" : "\(.*\)",/\1/p')
 AWS_SECRET_ACCESS_KEY=$(/bin/echo "${creds}" | /bin/sed -n 's/.*"SecretAccessKey" : "\(.*\)",/\1/p')
@@ -158,7 +161,9 @@ signature=$(sign "${signingKey}" "${toSign}")
 
 authorizationHeader="AWS4-HMAC-SHA256 Credential=${AWS_ACCESS_KEY_ID}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}"
 
-/usr/bin/curl -X POST -H "Content-Encoding: amz-1.0" -H "Authorization: ${authorizationHeader}" -H "Content-Type: application/json" -H "x-amz-content-sha256: ${payloadHash}" -H "x-amz-date: ${isoTimestamp}" -H "x-amz-security-token: ${AWS_SESSION_TOKEN}" -H "x-amz-target: com.amazon.aws.sshaccessproxyservice.AWSEC2InstanceConnectService.PutEC2HostKeys" -d "${val}" "${endpoint}/PutEC2HostKeys/"
+# Attempt to publish host keys
+# 5 second timeout helps avoid choking launches in private subnets (see https://github.com/aws/aws-ec2-instance-connect-config/issues/8)
+/usr/bin/curl -sS -m 5 -X POST -H "Content-Encoding: amz-1.0" -H "Authorization: ${authorizationHeader}" -H "Content-Type: application/json" -H "x-amz-content-sha256: ${payloadHash}" -H "x-amz-date: ${isoTimestamp}" -H "x-amz-security-token: ${AWS_SESSION_TOKEN}" -H "x-amz-target: com.amazon.aws.sshaccessproxyservice.AWSEC2InstanceConnectService.PutEC2HostKeys" -d "${val}" "${endpoint}/PutEC2HostKeys/"
 
 unset AWS_SESSION_TOKEN
 unset AWS_SECRET_ACCESS_KEY
