Improving OCSP staple logic to skip certificates that are already in the installed CA bundle Migrating temporary files to tmpfs for performance Tightening permissions on temporary files - they are now only accessible to the owner and only have write permissions until no longer needed Hard-setting system binary paths for system calls to avoid ambiguity/PATH dependency

diff --git a/src/opt/aws/bin/parse_authorized_keys b/src/opt/aws/bin/parse_authorized_keys
--- a/src/opt/aws/bin/parse_authorized_keys
+++ b/src/opt/aws/bin/parse_authorized_keys
@@ -1,10 +1,21 @@
 #!/bin/sh
 
-# EC2 Instance Connect AuthorizedKeysCommand v 1.1.0
+# EC2 Instance Connect AuthorizedKeysCommand v 1.0.0
 
 # Reads authorized keys blob $3 and prints verified, unexpired keys
 # Openssl to use provided as $1
 # Signer public key file path provided as $2
+
+# Failure reporting & exit
+# Format: fail [is_debug] [message]
+fail () {
+    if [ "$1" = true ] ; then
+        /bin/echo "${2}"
+    else
+        /usr/bin/logger -i -p authpriv.info "${2}"
+    fi
+    exit 1
+}
 
 # Helper to determine if a string starts with a given prefix
 # Format: startswith [string] [prefix]
@@ -15,21 +26,18 @@ startswith () {
 # Helper function to strip out a prefix from a string
 # Format: removeprefix [string] [prefix]
 removeprefix () {
-    printf '%s' "${1#${2}}"
+    /usr/bin/printf '%s' "${1#${2}}"
 }
 
 # Helper to verify an arbitrary ocsp response body given the certificate and issuer
 # Format: verifyocsp [is_debug] [openssl command] [certificate] [issuer] [ocsp directory]
 verifyocsp() {
-    fingerprint=$($2 x509 -noout -fingerprint -sha1 -inform pem -in $3 | sed -n 's/SHA1 Fingerprint=\(.*\)/\1/p') 2>/dev/null
-    ocsp_out=$($2 ocsp -no_nonce -issuer $4 -cert $3 -VAfile $4 -respin $5/$fingerprint) 2>/dev/null
+    # First check if this cert is already trusted
+    cname=$($2 x509 -noout -subject -in $3 2>/dev/null | /bin/sed -n -e 's/^.*CN=//p')
+    fingerprint=$($2 x509 -noout -fingerprint -sha1 -inform pem -in $3  2>/dev/null | /bin/sed -n 's/SHA1 Fingerprint=\(.*\)/\1/p' | tr -d ':')
+    ocsp_out=$($2 ocsp -no_nonce -issuer $4 -cert $3 -VAfile $4 -respin $5/$fingerprint 2>/dev/null)
     if [ $? -ne 0 ] || ! startswith "${ocsp_out}" "${3}: good" ; then
-        if [ "$1" = true ] ; then
-            echo "CERTIFICATE ${fingerprint} FAILED OCSP CHECK"
-        else
-            logger -i -p authpriv.info "EC2 Instance Connect could not verify certificate ${fingerprint} has not been revoked. No keys have been trusted."
-        fi
-        exit 1
+        fail $1 "EC2 Instance Connect could not verify certificate ${cname} has not been revoked. No keys have been trusted."
     fi
 }
 
@@ -66,7 +74,7 @@ while getopts ":x:r:o:d:s:i:c:a:v:f:" o; do
             expected_key="${OPTARG}"
             ;;
         *)
-            echo "Usage: $0 [-x debug] [-r key read command] [-o openssl command] [-d tmpdir] [-s signer certificate] [-i instance id] [-c cname] [-a ca path] [-v ocsp dir] [-f key fingerprint]"
+            /bin/echo "Usage: $0 [-x debug] [-r key read command] [-o openssl command] [-d tmpdir] [-s signer certificate] [-i instance id] [-c cname] [-a ca path] [-v ocsp dir] [-f key fingerprint]"
             exit 1
             ;;
     esac
@@ -76,60 +84,78 @@ done
 if [ $# -lt 1 ] ; then
     # No args whatsoever
     # Unit test log (ignored by sshd)
-    echo "Usage: $0 [-x debug] [-r key read command] [-o openssl command] [-d tmpdir] [-s signer certificate] [-i instance id] [-c cname] [-a ca path] [-v ocsp dir] [-f key fingerprint]"
+    /bin/echo "Usage: $0 [-x debug] [-r key read command] [-o openssl command] [-d tmpdir] [-s signer certificate] [-i instance id] [-c cname] [-a ca path] [-v ocsp dir] [-f key fingerprint]"
     # System log
-    logger -i -p authpriv.info "Unable to run EC2 Instance Connect: insufficient args provided.  Please check your sshd configuration."
+    /usr/bin/logger -i -p authpriv.info "Unable to run EC2 Instance Connect: insufficient args provided.  Please check your sshd configuration."
     exit 1
 fi
 
 # Verify the signer certificate we have been provided - CN, trust chain, and revocation status
 
-# Split the chain into pieces and simultaneously build the intermediate trust chain
-echo "${signer}" | awk -v dir="${tmpdir}" 'split_after==1{n++;split_after=0} /-----END CERTIFICATE-----/ {split_after=1} {print > dir "/cert" n ".pem"}'
-cat "${ca_path}" $(find $tmpdir -maxdepth 1 -type f -name "cert*.pem" -regextype sed -regex ".*/cert[0-9]\+\.pem$") > $tmpdir/ca-trust.pem
+# Split the chain into pieces
+echo "${signer}" | /usr/bin/awk -v dir="${tmpdir}" 'split_after==1{n++;split_after=0} /-----END CERTIFICATE-----/ {split_after=1} {print > dir "/cert" n ".pem"}'
+
+# We want visibility into the CA bundle so we can skip verifying entries in the chain that are already trusted
+ca_bundles_dir=$(/bin/mktemp -d $tmpdir/tmp-XXXXXXXX)
+/bin/chmod 700 $ca_bundles_dir
+end=$(/usr/bin/find $tmpdir -maxdepth 1 -type f -name "cert*.pem" -regextype sed -regex ".*/cert[0-9]\+\.pem" | wc -l)
+if [ $(/usr/bin/expr $end) -gt 0 ] ; then
+    for i in `/usr/bin/seq 1 $end` ; do
+        subject=$($OPENSSL x509 -noout -subject -in "${tmpdir}/cert$i.pem" | /bin/sed -n -e 's/^.*CN=//p')
+        # Try to pull this CN from the CA bundle
+        /bin/sed -n -e '/#[[:space:]]'"$subject"'$/,$p' "${ca_path}" | /bin/sed '/-----END[[:space:]]CERTIFICATE-----.*/,$d' | /bin/sed -n '1!p' > "${ca_bundles_dir}/${subject}"
+        if [ -s "${ca_bundles_dir}/${subject}" ] ; then
+            /bin/echo "-----END CERTIFICATE-----" >> "${ca_bundles_dir}/${subject}"
+        else
+            /bin/rm -f "${ca_bundles_dir}/${subject}"
+        fi
+    done
+fi
+
+# Build the intermediate trust chain
+cat $(/usr/bin/find $tmpdir -maxdepth 1 -type f -name "cert*.pem" -regextype sed -regex ".*/cert[0-9]\+\.pem$") "${ca_path}" > $tmpdir/ca-trust.pem
+/bin/chmod 400 "${tmpdir}/ca-trust.pem"
 
 # Verify the CN
-signer_cn=$($OPENSSL x509 -noout -subject -in $tmpdir/cert.pem | sed -n -e 's/^.*CN=//p')
+signer_cn=$($OPENSSL x509 -noout -subject -in $tmpdir/cert.pem | /bin/sed -n -e 's/^.*CN=//p')
 if [ "${signer_cn}" != "${expected_cn}" ] ; then
-    if [ "${is_debug}" = true ] ; then
-        echo "SIGNER CERTIFICATE NOT RECOGNIZED"
-    else
-        logger -i -p authpriv.info "EC2 Instance Connect encountered an unrecognized signer certificate. No keys have been trusted."
-    fi
-    exit 1
+    fail $is_debug "EC2 Instance Connect encountered an unrecognized signer certificate. No keys have been trusted."
 fi
 
 # Verify the trust chain
 verify_out=$($OPENSSL verify -x509_strict -CApath /dev/null -CAfile $tmpdir/ca-trust.pem $tmpdir/cert.pem)
 if [ $? -ne 0 ] || [ "${verify_out}" != "${tmpdir}/cert.pem: OK" ] ; then
-    if [ "${is_debug}" = true ] ; then
-        echo "SIGNER CERTIFICATE NOT TRUSTED"
-    else
-        logger -i -p authpriv.info "EC2 Instance Connect could not verify the signer trust chain. No keys have been trusted."
-    fi
-    exit 1
+    fail $is_debug "EC2 Instance Connect could not verify the signer trust chain. No keys have been trusted."
 fi
 
 # Verify no certificates have been revoked
 # Iterate from first to second-to-last cert & validate OCSP staples
-mv $tmpdir/cert.pem $tmpdir/cert0.pem # Better naming consistency for loop
-end=$(find $tmpdir -maxdepth 1 -type f -name "cert*.pem" -regextype sed -regex ".*/cert[0-9]\+\.pem" | wc -l)
-end=$(( $end - 1))
-for i in `seq 0 $(( $end - 1 ))` ; do
+/bin/mv $tmpdir/cert.pem $tmpdir/cert0.pem # Better naming consistency for loop
+for i in `/usr/bin/seq 0 $(( $end - 1 ))` ; do
+    subject=$($OPENSSL x509 -noout -subject -in "${tmpdir}/cert${i}.pem" | /bin/sed -n -e 's/^.*CN=//p')
+    if [ -f "${ca_bundles_dir}/${subject}" ] ; then
+        # If we encounter a certificate that's in the CA bundle we can skip the rest as implicitly trusted
+        hash=$($OPENSSL x509 -hash -noout -in "${tmpdir}/cert${i}.pem" 2>/dev/null)
+        trusted_hash=$($OPENSSL x509 -hash -noout -in "${ca_bundles_dir}/${subject}" 2>/dev/null)
+        fingerprint=$($OPENSSL x509 -noout -fingerprint -sha1 -in "${tmpdir}/cert${i}.pem" 2>/dev/null | /bin/sed -n 's/SHA1 Fingerprint=\(.*\)/\1/p' | tr -d ':')
+        trusted_fingerprint=$($OPENSSL x509 -noout -fingerprint -sha1 -in "${ca_bundles_dir}/${subject}" 2>/dev/null | /bin/sed -n 's/SHA1 Fingerprint=\(.*\)/\1/p' | tr -d ':')
+        pkey=$($OPENSSL x509 -pubkey -noout -in "${tmpdir}/cert${i}.pem")
+        trusted_pkey=$($OPENSSL x509 -pubkey -noout -in "${ca_bundles_dir}/${subject}" )
+        if [ "${hash}" = "${trusted_hash}" ] && [ "${fingerprint}" = "${trusted_fingerprint}" ] && [ "${pkey}" = "${trusted_pkey}" ] ; then
+            # Already trusted, no need to OCSP verify
+            break
+        fi
+    fi
     verifyocsp $is_debug $OPENSSL "${tmpdir}/cert${i}.pem" "${tmpdir}/cert$(( $i + 1)).pem" "${ocsp_dir_path}"
 done
-# We still need to verify the last certificate's OCSP staple with the CA as the issuer
-verifyocsp $is_debug $OPENSSL "${tmpdir}/cert${end}.pem" "${ca_path}" "${ocsp_dir_path}"
+
+# At this point we no longer need the CA information
+/bin/rm -rf $ca_bundles_dir
 
 # Extract cert public key
-echo "${signer}" | $OPENSSL x509 -pubkey -noout > "${tmpdir}/pubkey" 2>/dev/null
+/bin/echo "${signer}" | $OPENSSL x509 -pubkey -noout > "${tmpdir}/pubkey" 2>/dev/null
 if [ $? -ne 0 ] ; then # $? must be numeric 0-255 and requires no quote escaping
-    if [ "${is_debug}" = true ] ; then
-        echo "FAILED TO GET SIGNER PUBLIC KEY"
-    else
-        logger -i -p authpriv.info "EC2 Instance Connect failed to extract the public key from the signer certificate. No keys have been trusted."
-    fi
-    exit 1
+    fail $is_debug "EC2 Instance Connect failed to extract the public key from the signer certificate. No keys have been trusted."
 fi
 
 
@@ -138,7 +164,7 @@ fi
 if [ ! -z ${expected_key+x} ] ; then
     # An expected fingerprint was given
     if [ "${is_debug}" = false ] ; then
-        logger -i -p authpriv.info "Querying EC2 Instance Connect keys for matching fingerprint: ${expected_key}"
+        /usr/bin/logger -i -p authpriv.info "Querying EC2 Instance Connect keys for matching fingerprint: ${expected_key}"
     fi
 fi
 
@@ -159,10 +185,10 @@ output=$(eval "${read_command}" | (
         pathprefix="${tmpdir}/${count}"
 
         # Clear our temp buffers to prevent any sort of injection
-        rm -f "${pathprefix}-key"
-        rm -f "${pathprefix}-signedData"
-        rm -f "${pathprefix}-sig"
-        rm -f "${pathprefix}-decoded"
+        /bin/rm -f "${pathprefix}-key"
+        /bin/rm -f "${pathprefix}-signedData"
+        /bin/rm -f "${pathprefix}-sig"
+        /bin/rm -f "${pathprefix}-decoded"
 
         # Pre-initialize key validation fields
         timestamp=0
@@ -170,6 +196,8 @@ output=$(eval "${read_command}" | (
         caller=""
         request=""
         # We do not pre-initialize the actual key or signature fields
+        /bin/touch "${pathprefix}-signedData"
+        /bin/chmod 600 "${pathprefix}-signedData"
 
         # Loop to read keys & parse out values
         # This is not sub-shelled as we want to maintain variable scope with the outer loop
@@ -191,7 +219,7 @@ output=$(eval "${read_command}" | (
 
             # We verify on all fields in-order, whether we recognize them or not.  Similarly, we don't force fields not present.
             # As such we always add this to the signature verification file
-            printf '%s\n' "${line}" >> "${pathprefix}-signedData"
+            /usr/bin/printf '%s\n' "${line}" >> "${pathprefix}-signedData"
 
             # Read the next line
             read -r line
@@ -200,27 +228,33 @@ output=$(eval "${read_command}" | (
         # At this point, line should contain the key
         if startswith "${line}" "ssh" ; then
             key="${line}"
-            printf '%s\n' "${key}" >> "${pathprefix}-signedData"
+            /usr/bin/printf '%s\n' "${key}" >> "${pathprefix}-signedData"
+
+            # At this point we do not need to modify signedData
+            /bin/chmod 400 "${pathprefix}-signedData"
 
             # Read key signature - may be multi-line
             encodedsigfile="${pathprefix}-sig"
+            /bin/touch "${encodedsigfile}"
+            /bin/chmod 600 "${encodedsigfile}"
             read -r sigline
             while [ "${sigline}" != "" ]
             do
-                printf '%s\n' "${sigline}" >> "${encodedsigfile}"
+                /usr/bin/printf '%s\n' "${sigline}" >> "${encodedsigfile}"
                 read -r sigline
             done
+            /bin/chmod 400 "${encodedsigfile}"
 
             # Begin validation
-            printf '%s\n' "${key}" > "${pathprefix}-key"
-            fingerprint=$(ssh-keygen -lf "${pathprefix}-key" | cut -d ' ' -f 2) # Get only the actual fingerprint, ignore key size & source
-            expiration=$(expr "${timestamp}")
+            /usr/bin/printf '%s\n' "${key}" > "${pathprefix}-key"
+            fingerprint=$(/usr/bin/ssh-keygen -lf "${pathprefix}-key" | cut -d ' ' -f 2) # Get only the actual fingerprint, ignore key size & source
+            expiration=$(/usr/bin/expr "${timestamp}")
             # If we were told to expect a specific key and this isn't it, skip it
             if [ -z "${expected_key}" ] || [ "$fingerprint" = "${expected_key}" ] ; then
                 # Check instance ID matches & timestamp is still valid
                 if [ "${current_instance_id}" = "${instance_id}" ] && [ $expiration -gt $curtime ] ; then
                     # Decode the signature
-                    base64 --decode "${encodedsigfile}" > "${pathprefix}-decoded" 2>/dev/null
+                    /usr/bin/base64 --decode "${encodedsigfile}" > "${pathprefix}-decoded" 2>/dev/null
                     # Verify signature
                     $OPENSSL dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:32 -verify "${tmpdir}/pubkey" -signature "${pathprefix}-decoded" "${pathprefix}-signedData" 1>/dev/null 2>/dev/null
                     if [ $? -eq 0 ] ; then
@@ -233,9 +267,11 @@ output=$(eval "${read_command}" | (
                         if [ "${caller}" != "" ] ; then
                             callermessage="${callermessage}, for IAM principal: ${caller}"
                         fi
-                        logger -i -p authpriv.info "${callermessage}"
+                        if [ "$is_debug" = false ] ; then
+                            /usr/bin/logger -i -p authpriv.info "${callermessage}"
+                        fi
                         # Return key to the ssh daemon
-                        echo "${key}"
+                        /bin/echo "${key}"
                         exitcode=0
                     fi
                 fi
@@ -249,12 +285,12 @@ output=$(eval "${read_command}" | (
         fi
 
         # Clean up any tempfiles
-        rm -f "${pathprefix}-key"
-        rm -f "${pathprefix}-signedData"
-        rm -f "${pathprefix}-sig"
-        rm -f "${pathprefix}-decoded"
+        /bin/rm -f "${pathprefix}-key"
+        /bin/rm -f "${pathprefix}-signedData"
+        /bin/rm -f "${pathprefix}-sig"
+        /bin/rm -f "${pathprefix}-decoded"
 
-        count=$(expr "${count}" + 1)
+        count=$(/usr/bin/expr "${count}" + 1)
     done
     # This is the loop subprocess's exit code, not the script's
     exit $exitcode
@@ -262,6 +298,6 @@ output=$(eval "${read_command}" | (
 # Re-capture the exit code
 exitcode=$?
 # Print keys & exit
-rm -rf "${tmpdir}/pubkey"
-echo "${output}"
+/bin/rm -rf "${tmpdir}/pubkey"
+/bin/echo "${output}"
 exit $exitcode
